apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-green
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
      version: green
  template:
    metadata:
      labels:
        app: spring-boot-app
        version: green
    spec:
      containers:
        - image: kubernetes-assigment:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: spring-boot-app
          ports:
            - containerPort: 8080
          resources: {}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3